/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.risc.server;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    //@RunWith(PowerMockRunner.class)
    // @PrepareForTest({BeanUtils.class})

    @Test
    public void test_main(){
        // Start a new TestLoopBackServer in a separate thread
        try{
            Thread server=make_server_thread_helper();
            server.start();
            Thread th0 = make_test_player_thread_helper("0");
            th0.start();
            Thread th1 = make_test_player_thread_helper("1");
            th1.start();
            App.main(new String[0]);
        }catch(Exception e){
            return;
        }

    }

    private Thread make_server_thread_helper() {
      Thread th = new Thread() {
        @Override
        public void run() {
          try {
            App.main(new String[0]);
          } catch (Exception e) {
          }
        }
      };
      return th;
    }

    private Thread make_test_player_thread_helper(String id) {
        Thread th = new Thread() {
          @Override
          public void run() {
            try {
              String[] args={id}; 
              TestPlayer.main(args);
            } catch (Exception e) {
            }
          }
        };
        return th;
      }
}
