/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.risc.client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class App {
    public static void main(String[] args) throws IOException,ClassNotFoundException{
        SocketClient client=new SocketClient(12345,"localhost");
        BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
        GamePlayer<String> player=new V1GamePlayer<String>(-1, client, input, System.out);
        player.initGame();
        player.pickTerritory();
        player.deployUnits();
        player.doPlayPhase();
    }
}
