/**
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.risc.client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.fxml.*;

/**
 * This is the App class for client project
 */
public class App extends Application{

  /** window to display */
  private Stage window;

  /**
   * The start point of this app.
   * 
   * @param primaryStage window to display
   */
  @Override
  public void start(Stage primaryStage) throws Exception {
    this.window = primaryStage;
    showStartView(window);
  }

  /**
   * This method display the start view
   * 
   * @param window to display
   */
  public void showStartView(Stage window) throws IOException{
    PageLoader loader=new PageLoader(window,null);
    loader.showStartPage();
  }

  public static void main(String[] args) {
    launch(args);
  }

  
}






